### ISSUE TITLE
Aufgabe 4 // create Java Code

### ISSUE THREAD

**Issue by SPortugall** [sweIhm-ws2018-19/skillproject-fr-26#1]
![unbenannt](https://user-images.githubusercontent.com/43878655/47215536-08c39c00-d3a2-11e8-900a-ef2341b11963.PNG)

Wie lautet der zum dargestellten Klassendiagramm passende Java Code?

Review macht @SPortugall

**Comment by SPortugall** [comment]
test

**Comment by SPortugall** [comment]
Ich habe dem vorhandenen commit folgendes hinzugefügt:
- leere Klasse "GeldBetrag" // sie war zwar nicht direkt angegeben im UML, aber zwingend notwendig, denn sie ist als DatenTyp in der Klasse Konto und andernfalls würde der javacode einen Fehler beinhalten => meiner Meinung nach darf kein fehlerhafter Code gepusht werden
- 1..* assoziation versucht darzustellen durch einen Konstruktor, der das jeweilige array initialisiert. Es ist zwar dadurch keine Garantie für min 1 Element, aber ab nun kann dies per logic abgefangen werden. => daher auch dieser punkt meiner Meinung nach zwingend notwendig

**Comment by hupling** [comment]
Review erfolgreich
