### ISSUE TITLE
1. Systemidee auf Startseite des Wikis

### ISSUE THREAD

**Issue by hupling** [sweIhm-ws2018-19/skillproject-fr-26#12]

**Comment by hupling** [comment]
Done

**Comment by haerrel** [comment]
Unklarheiten beseitigen:
* Systemidee: Notierte Fragen im Wiki klären (https://github.com/sweIhm-ws2018-19/skillproject-fr-26/wiki/Systemidee---MUCtivities)
* Kann eine Systemidee nachträglich angepasst werden?

**Comment by haerrel** [comment]
Anmerkungen von Frau Socher:
**bayrisch** Damit man nicht gezwungen ist dies zu implementieren, formuliert man in der Systemidee das Feature möglichst vage. So kann es nur ein einfaches "Servus" sein, dass das Feature schon erfüllt. Natürlich kann es auch je nach Zeit aufwendiger implementiert sein (z.B. via SSML)

**Systemidee** oberflächlich, so dass PO und Entwickler eine gemeinsame Idee davon Teilen (egal ob ausgeschrieben oder als Aufzählungen)

**Preis** Gesamtkalkulation für die Entwicklungskosten (Team + POs)

**Problembeschreibung** nicht in Bezug auf das Fach (weil wir ein Skill programmieren müssen),  sondern eher darauf, dass es so was noch nicht gibt.
