### ISSUE TITLE
4. Prototyp mit gestoryline.com erstellen

### ISSUE THREAD

**Issue by hupling** [sweIhm-ws2018-19/skillproject-fr-26#13]

**Comment by hupling** [comment]
Done. @LisaWenzl @VanessaGMeiler haben des schon in ihrer Vorlesung erstellt gehabt.

**Comment by hupling** [comment]
Es müssen noch Kleinigkeiten geändert werden. Besprechen wir am Freitag

**Comment by haerrel** [comment]
Für Freitag:

**Comment by haerrel** [comment]
Für Freitag:
* Modell fertig?
* Modell zusammenstauchen und finalisieren
* ggf. erweitern

**Comment by SPortugall** [comment]
Done

**Comment by hupling** [comment]
https://getstoryline.com/shared/projects/027f1a47fd293a05153bac5346cddbd9438b8ca6

**Comment by hupling** [comment]
url changed: https://app.invocable.com/shared/projects/027f1a47fd293a05153bac5346cddbd9438b8ca6
