### ISSUE TITLE
5. a) Anwendungsfalldiagramm

### ISSUE THREAD

**Issue by hupling** [sweIhm-ws2018-19/skillproject-fr-26#14]

**Comment by SPortugall** [comment]
![untitled diagram](https://user-images.githubusercontent.com/43878655/48517090-81b0f900-e865-11e8-8ef8-747486af05bf.png)


@hupling  please Review

**Comment by SPortugall** [comment]
Ich habe mir ein Beispiel an dem Diagramm aus den Folien zur Analyse genommen.

**Comment by SPortugall** [comment]
![untitled diagram 1](https://user-images.githubusercontent.com/43878655/48582195-1712c280-e924-11e8-8db1-09328ed3ed9a.png)
