### ISSUE TITLE
6. b) ii. Beschreibung der User Stories

### ISSUE THREAD

**Issue by hupling** [sweIhm-ws2018-19/skillproject-fr-26#17]

**Comment by haerrel** [comment]
ToDo:
UserStorys #25 #27 noch nicht komplett ausdefiniert. Es gibt noch winzige Unklarheiten.
In Bearbeitung bei @LisaWenzl @VanessaGMeiler

**Comment by haerrel** [comment]
Unklarheiten mit POs geklärt
