### ISSUE TITLE
7. Fachklassenmodell (Analyseklassenmodell)

### ISSUE THREAD

**Issue by hupling** [sweIhm-ws2018-19/skillproject-fr-26#19]

**Comment by hupling** [comment]
![image](https://user-images.githubusercontent.com/11695964/48369330-84b9b700-e6b6-11e8-81b8-f81cb2104387.png)
@SPortugall please review!!!

**Comment by hupling** [comment]
https://github.com/sweIhm-ws2018-19/skillproject-fr-26/wiki/0.-Sprint---Anforderungsanalyse-und-Product-Backlog#aufgabe-7

**Comment by SPortugall** [comment]
sieht gut aus, hätte dem nichts hinzuzufügen da ich auch kein anderes Beispiel eines Fachklassenmodells irgendwo finde.

**Comment by hupling** [comment]
![image](https://user-images.githubusercontent.com/11695964/48536815-fdd02e80-e8af-11e8-8e0c-10999871e15f.png)
