### ISSUE TITLE
2. Skill Startseite / Systemidee

### ISSUE THREAD

**Issue by haerrel** [sweIhm-ws2018-19/skillproject-fr-26#20]
Erstellen Sie im Wiki zu Ihrem Github Repository eine (neue) Startseite für die Systemidee Ihres Praktikumsprojekts. Schreiben Sie Ihre Systemidee auf die Startseite des Wikis

**Comment by haerrel** [comment]
https://github.com/sweIhm-ws2018-19/skillproject-fr-26/wiki/Systemidee---MUCtivities

**Comment by hupling** [comment]
#12 Das gleiche Issue
