### ISSUE TITLE
Wetter-Vorhersage

### ISSUE THREAD

**Issue by haerrel** [sweIhm-ws2018-19/skillproject-fr-26#21]
Beschreibung:
Als Alexa-Benutzer möchte ich wetterabhängige Aktivitätsvorschläge erhalten

Akzeptanzkriterien:
- Erfassung der Wetterlage für den gesamten Tag
- Erfassung bei Ausführung des Skills

**Comment by haerrel** [comment]
Ob gutes oder schlechtes Wetter ist bestimme ich anhand der ID des Wettericons.
https://openweathermap.org/weather-conditions

Gutes Wetter: id < "03x"
Schlechtes Wetter: alles andere

@VanessaGMeiler @LisaWenzl ist diese Wetterbestimmung ausreichend? sollen wir die Wetterbestimmung an anderen Kriterien bestimmen?

**Comment by hupling** [comment]
von @VanessaGMeiler : Wir haben auch noch überlegt, ob wir das Wetter und der daraus folgende Vorschlag ob drinnen oder draußen anhand der Temperatur festmachen sollen
Somit umgehen wir zb das Problem, dass im Winter Aktivitäten vorgeschlagen werden, die nur von Frühling bis Herbst möglich sind
**todo**:

-  Formulierungen einpflegen,
- Gutes Wetter: (Temperatur > 15°C && sonnig), sonst Schlechtes Wetter

**Comment by haerrel** [comment]
Logik für gutes Wetter im Code entsprechend angepasst

**Comment by haerrel** [comment]
![image](https://user-images.githubusercontent.com/38572411/49166332-6c42d100-f333-11e8-9302-b5ce3369e384.png)

**Comment by haerrel** [comment]
@SPortugall bitte reviewn

**Comment by SPortugall** [comment]
Implemented in pair-programming -> review done
