### ISSUE TITLE
Lokalität abfragen

### ISSUE THREAD

**Issue by haerrel** [sweIhm-ws2018-19/skillproject-fr-26#22]
Beschreibung:
Als Alexa-Benutzer möchte ich gefragt werden, ob ich drinnen oder draußen etwas unternehmen möchte, um die Aktivitätsvorschläge einzugrenzen

Akzeptanzkriterien:
- Benutzerabfrage, ob Aktivität drinnen oder draußen stattfinden soll
- Vorschlag, ob drinnen oder draußen anhand der Wetter-Vorhersage

**Comment by hupling** [comment]
Todo: 
- Formulierungen einpflegen
- Es soll die Möglichkeit geben. Vor und Zurück zu Springen. z. B. von der Dauer zurück zur Lokalität

**Comment by SPortugall** [comment]
@jwalteri und ich haben uns bemüht herauszufinden, wie der Skill den aktuellen Standort abfragen kann.
Aufgrund von erschwertem/unmöglichem Debugging des Skills und so gut wie keiner Dokumentation von der Alexa API, blieb uns nichts über, als zu dem Schluss zu kommen, dass es nicht möglich ist, in angemessener Zeit und mäßigen Kosten der eigenen Nerven und somit der Gesundheit, den Standort abzufragen.

**Comment by jwalteri** [comment]
s.o.

**Comment by haerrel** [comment]
![image](https://user-images.githubusercontent.com/38572411/49165892-84662080-f332-11e8-8306-d25edb2fde2b.png)

**Comment by jwalteri** [comment]
Please review.

**Comment by jwalteri** [comment]
@hupling Please review.

**Comment by hupling** [comment]
is ok.
