### ISSUE TITLE
Dauer abfragen

### ISSUE THREAD

**Issue by haerrel** [sweIhm-ws2018-19/skillproject-fr-26#23]
Beschreibung:
Als Alexa-Benutzer möchte ich gefragt werden, wie lange die Aktivität sein soll, um die 
Aktivitätsvorschläge einzugrenzen

Akzeptanzkriterien:
- Benutzerabfrage, ob ein paar Stunden oder den ganzen Tag

**Comment by hupling** [comment]
Todo:
- Formulierungen einpflegen
- Es soll die Möglichkeit geben. Vor und Zurück zu Springen. z. B. von der Dauer zurück zur Lokalität

**Comment by haerrel** [comment]
![image](https://user-images.githubusercontent.com/38572411/49167296-64842c00-f335-11e8-818a-8469b75b13e5.png)

**Comment by haerrel** [comment]
Reviewed durch Pair-Programming
