### ISSUE TITLE
Kategorie abfragen

### ISSUE THREAD

**Issue by haerrel** [sweIhm-ws2018-19/skillproject-fr-26#24]
Beschreibung:
Als Alexa-Benutzer möchte ich zwischen mehreren Aktivitätskategorien wählen können, um die Aktivitätsvorschläge einzugrenzen

Akzeptanzkriterien:
- Benutzerabfrage, ob Kultur, Sport, Spaß

**Comment by hupling** [comment]
Todo:
- Formulierungen einpflegen
- Es soll die Möglichkeit geben. Vor und Zurück zu Springen. z. B. von der Dauer zurück zur Lokalität

**Comment by hupling** [comment]
Bei der Kultur-Kategorien gibt es noch Unterkategorien

**Comment by haerrel** [comment]
![image](https://user-images.githubusercontent.com/38572411/49167545-dfe5dd80-f335-11e8-9e7b-42823c888860.png)

**Comment by haerrel** [comment]
Reviewed durch Pair-Programming
