### ISSUE TITLE
Aktivitäten vorschlagen

### ISSUE THREAD

**Issue by haerrel** [sweIhm-ws2018-19/skillproject-fr-26#25]
Beschreibung:
Als Alexa-Benutzer möchte ich basierend auf meinen Eingrenzungen mehrere Aktivitätsvorschläge erhalten

Akzeptanzkriterien: 
- einen konkreten Vorschlag nennen und nachfragen, ob dieser Vorschlag interessant ist
- bei Desinteresse einen anderen Vorschlag nennen
- wenn kein weiterer Aktivitäts-Vorschlag vorhanden (nach mehrmaligem ablehnen der vorgeschlagenen Aktivitäten), dann wir der Benutzer darauf hin gewiesen (Formulierung von POs verwenden)

**Comment by haerrel** [comment]
Beschreibung der UserStory nach Absprache mit @VanessaGMeiler angepasst

**Comment by hupling** [comment]
von @LisaWenzl und @VanessaGMeiler  vorläufiger Entwurf der Aktivitäten: [word dokument](https://github.com/sweIhm-ws2018-19/skillproject-fr-26/blob/master/MUCtivities/Dokumente/Liste%20Aktivit%C3%A4ten.docx)

**Comment by hupling** [comment]
![image](https://user-images.githubusercontent.com/11695964/48864949-677b9b80-edce-11e8-80b6-1678c2fd206d.png)
@hupling Tabellenvorschlag zum Speichern der Aktivitäten in der Datenbank

**Comment by hupling** [comment]
Beim Tipp des Tages soll eine zufällige Kategorie ausgegeben werden.
Todo: 
-Einpflegen der Datensätze in die Datenbank + Anbindung des Skills an die Datenbank <br>(Datenbank= DynamoDB oder Csv Datei)
-Zusätzliches Feature: beim Vorschlag Bowling, soll die Bowling Bahn mit der kürzesten Entfernung ausgegeben werden

**Comment by haerrel** [comment]
@hupling @jwalteri 
Siehe Commit: e900de5e96b0153b3a91e5e4456588096f09dd24
- JSON-Datenbank aktualisiert
- Ausgabe von "Tipp des Tages" mit eingebaut
- Ausgabe eines ersten Aktivitäts-Vorschlags mit eingebaut

**Comment by hupling** [comment]
![0f9cbaf3-6fc0-42b4-99d8-d9ab9c57c182](https://user-images.githubusercontent.com/11695964/49161344-f20d4f00-f328-11e8-8e45-15764277c4e4.jpg)

**Comment by hupling** [comment]
![32356cc2-3366-4edf-8b61-ca2323d20453](https://user-images.githubusercontent.com/11695964/49161360-f89bc680-f328-11e8-8706-edd0ac39a739.jpg)

**Comment by haerrel** [comment]
![image](https://user-images.githubusercontent.com/38572411/49168010-eb85d400-f336-11e8-8651-581cb47e523d.png)

**Comment by haerrel** [comment]
Reviewed durch Pair-Programming
