### ISSUE TITLE
Navigations-Informationen

### ISSUE THREAD

**Issue by haerrel** [sweIhm-ws2018-19/skillproject-fr-26#27]
Beschreibung:
Als Alexa-Benutzer möchte ich eine Navigation via ÖPNV angesagt bekommen, um einfacher zur Örtlichkeit der Aktivität zu kommen

Akzeptanzkriterien:
- Navigation anhand aktueller MVV/MVG/ÖPNV Informationen
- Ausgabe des Navigationsergebnisses

**Comment by haerrel** [comment]
Beschreibung der UserStory nach Absprache mit @VanessaGMeiler angepasst

**Comment by haerrel** [comment]
Mit @VanessaGMeiler @LisaWenzl besprochen:
Priorität gering, von allen Userstories wird diese als letztes bearbeitet

**Comment by haerrel** [comment]
![image](https://user-images.githubusercontent.com/38572411/49168711-63083300-f338-11e8-8705-581f9c55c1a2.png)

**Comment by hupling** [comment]
mit POs vereinbart, dass nicht mehr machbar in der Zeit 
--> closed
