### ISSUE TITLE
Begrüßung

### ISSUE THREAD

**Issue by haerrel** [sweIhm-ws2018-19/skillproject-fr-26#28]
Beschreibung:
Als Alexa-Benutzer möchte ich begrüßt werden

Akzeptanzkriterien:
- Begrüßungsdialog wird ausgegeben

**Comment by hupling** [comment]
**todo** einpflegen der Formulierungen von @LisaWenzl + @VanessaGMeiler

**Comment by haerrel** [comment]
Reviewed durch Pair-Programming
