### ISSUE TITLE
Umbau der Dialogstruktur

### ISSUE THREAD

**Issue by haerrel** [sweIhm-ws2018-19/skillproject-fr-26#35]
Die aktuelle JSON- und Alexa-Console-basierte Dialogstruktur (Delegate Directives) anhand von mehreren Slots in einem einzigen Intent auflösen in mehrere Intents und somit auch mehrere Java-Klassen umbauen.

## Ziel
aktuell ist der Dialog "straight-forward"
gewünscht ist jedoch auch zurück zu einem vorherigen Intent zu springen

**Comment by jwalteri** [comment]
Die neue Version ist über "Das ist ein Testlauf" aufrufbar, während die alte Version noch mit "Mir ist langweilig" aufrufbar ist. Es fehlt noch, dass die Attribute, welche von Alexa zurückgeschickt werden, verarbeitet werden, sodass eine Aktivität vorgeschlagen werden kann.

**Comment by hupling** [comment]
Hier ist der neue Dialogverlauf:
![bf055dc4-13b6-4210-9cfc-753ef765013f](https://user-images.githubusercontent.com/11695964/49161872-056cea00-f32a-11e8-81af-7853e1122cfc.jpg)

**Comment by jwalteri** [comment]
Hier ist der Commit davon: c67ba33c1f59ccb90a872bd07d3090ec97c44e62

**Comment by haerrel** [comment]
Reviewed durch Pair-Programming

**Comment by jwalteri** [comment]
![aktivitatsdiagramm](https://user-images.githubusercontent.com/43862813/49872619-ec7c3280-fe19-11e8-8197-9e1d03775430.png)
