### ISSUE TITLE
Tipp des Tages (PRIO 3)

### ISSUE THREAD

**Issue by hupling** [sweIhm-ws2018-19/skillproject-fr-26#38]
1. Ausgabe des Tipp des Tages 
2. Weiter Informationen auf Wunsch ausgeben (wie gewohnt)

**Comment by haerrel** [comment]
https://github.com/sweIhm-ws2018-19/skillproject-fr-26/commit/0aa8f0ac469b0d869c6a6f48715ace526fcd2509
