### ISSUE TITLE
Wetter „Drinnen oder Draußen?“  (PRIO 5) 

### ISSUE THREAD

**Issue by hupling** [sweIhm-ws2018-19/skillproject-fr-26#40]
Aktuell: public static final String WEATHER_SUNNY = "Heute wird ein sonniger Tag. Möchtest du etwas draußen oder drinnen unternehmen?"; public static final String WEATHER_RAINY = "Heute ist ein greisliges Wetter draußen, am besten bleibst du heut drin oder magst du etwas draußen unternehmen?"; Statt „draußen oder drinnen“ eine YesNo-Abfrage mit entsprechendem Handling

**Comment by haerrel** [comment]
Reviewed durch Pair-Programming
