### ISSUE TITLE
Fehleingaben beim LocationIntent (siehe Word-Dokument mit Phrasen zu den Falscheingaben) (PRIO 7) 

### ISSUE THREAD

**Issue by hupling** [sweIhm-ws2018-19/skillproject-fr-26#41]
Reprompt Attribut für jede Klasse als Seasson Attribute einfügen

**Comment by hupling** [comment]
funktioniert noch nicht richtig. muss noch getestet werden

**Comment by haerrel** [comment]
Reviewed durch Pair-Programming
