### ISSUE TITLE
Synonyme Ja/Nein

### ISSUE THREAD

**Issue by LisaWenzl** [sweIhm-ws2018-19/skillproject-fr-26#49]
Allgemeine Ja/Nein Synonyme des Users sollen für verschiedene Intents im Dialog anwendbar sein (siehe Word Dokument Ja/Nein Synonyme)

**Comment by hupling** [comment]
![image](https://user-images.githubusercontent.com/11695964/49881218-18091800-fe2e-11e8-8eea-7b21ddd4be4e.png)
Alles wurde schön von @jwalteri  eingepflegt

**Comment by hupling** [comment]
Phasen wurden wieder geändert

**Comment by hupling** [comment]
hier könnt ihr neue ja/nein synoyme hinzufügen
![image](https://user-images.githubusercontent.com/11695964/50221462-76397c00-0395-11e9-8a12-4567f3ac2412.png)
