### ISSUE TITLE
Phrasen ändern

### ISSUE THREAD

**Issue by VanessaGMeiler** [sweIhm-ws2018-19/skillproject-fr-26#50]
- Begrüßung: 
1. Servus! Ich bin **das Münchner Kindl** und du kannst mich nach einem **personalisierten Vorschlag für eine Aktivität in München oder nach** dem Tipp des Tages fragen. **Was möchtest du wissen?**
2. Grias di! Frage mich nach einem personalisierten Vorschlag für eine **Aktivität** in München **oder nach**  dem Tipp des Tages und ich helfe dir sehr gerne weiter. Wonach suchst du?
3. Servus!  Wenn dir langweilig ist, bist du hier genau richtig. Möchtest du einen personalisierten Vorschlag für eine Aktivität in München erhalten oder den Tipp des Tages hören? **Du hast die Wahl**. 

-Tipp des Tages:
Der Tipp des Tages ist X. **Hättest du gerne mehr Informationen dazu?**

- Location/Wetter:
1. Heute ist Regen angesagt. Vielleicht sollten wir lieber nach einer Aktivität **drinnen** suchen. Bist du einverstanden? ("im Trockenen/" rauslöschen)

**Comment by haerrel** [comment]
@hupling buildest du bitte nochmal und lädst es in den AWS hoch?

**Comment by hupling** [comment]
Machen wir morgen alles. Vor der Stunde.
