### ISSUE TITLE
"Ende" - Verabschiedungsphrase fehlt

### ISSUE THREAD

**Issue by VanessaGMeiler** [sweIhm-ws2018-19/skillproject-fr-26#51]
Verabschiedung kommt nicht, wenn man "Ende" sagt.

**Comment by hupling** [comment]
![image](https://user-images.githubusercontent.com/11695964/49963196-968db480-ff17-11e8-83a8-0ca3744bedc7.png)
leider keine antwort bei whatsapp bekommen. darum ist das problem unklar
