### ISSUE TITLE
Kurze Verabschiedungsphrase bei allen Informationen

### ISSUE THREAD

**Issue by VanessaGMeiler** [sweIhm-ws2018-19/skillproject-fr-26#52]
Jedes Mal, wenn eine Information zu einer Aktivität ausgegeben wird, soll noch die Phrase
"Viel Spaß und bis zum nächsten Mal! Pfiad di, Servus!" oder als Alternative die Phrase
"Viel Spaß in München und bis zum nächsten Mal! Pfiat di, mach’s gut!" angehängt werden.

**Comment by haerrel** [comment]
Verstehe ich den Aufbau richtig?
Alexa: Wie wäre es mit ....? Möchtest du dazu mehr Informationen=
User: Ja!
Alexa: %Ausgabe von weiteren Informationen zur Aktivität% + %eine der oben genannten phrasen%
In welchem Zustand soll das Skill dann danach sein?
- Beendet? Also sodass wieder "Öffne Muctivities" gesagt werden müsste.
- Oder soll es auf Phrasen wie "mir ist langweilig" bzw "Tipp des Tages" warten?

**Comment by VanessaGMeiler** [comment]
Eigentlich beendet, man hat ja dann seine Aktivität gefunden, bin aber nicht ganz sicher was du im zweiten Punkten mit „warten“ meinst

**Comment by LisaWenzl** [comment]
Besser wäre wahrscheinlich wenn es wartet - wenn die "Zurück"Schritte implementiert sind, könnte der Nutzer das an der Stelle evtl. sagen - ist das dann möglich?
