### ISSUE TITLE
Vorschläge ausschließen, wenn sie schon mal genannt wurden

### ISSUE THREAD

**Issue by VanessaGMeiler** [sweIhm-ws2018-19/skillproject-fr-26#53]
Vorschläge die schon genannt wurden ausschließen, um Wiederholungen zu vermeiden

**Comment by VanessaGMeiler** [comment]
Vorschläge die schon genannt wurden ausschließen, um Wiederholungen zu vermeiden

**Comment by haerrel** [comment]
Hast du hierzu einen Screenshot (samt JSON-Input und JSON-Output).
Nach Programmlogik entfernen wir nämlich immer den soeben genannten Vorschlag aus der Auswahl für die nächst genannten Vorschläge. Das haben wir auch verifiziert.

**Comment by hupling** [comment]
da keine weiteren Informationen
--> close
--> wenn das Problem noch besteht reopen
