### ISSUE TITLE
Bayrische Lautschrift

### ISSUE THREAD

**Issue by LisaWenzl** [sweIhm-ws2018-19/skillproject-fr-26#57]
- Grias di: gRi:6_^sdI
- Greisliges: gRaIzlICEz
- Basst: basd
- Guad: gu:6_^d
- Super Gschicht: sUbb6 gSICd
- Ja mei: jO6_^ maI
- Zefix: ts@"fIks
- Mei, des wird a Gaudi: maI de:z vE6_^d a gaUde:
- Mei, des wird gspassig: maI de:z vE6_^d gSbasIg
- pfiad di: pfi:6_^d di:

**Comment by hupling** [comment]
https://developer.amazon.com/de/docs/custom-skills/speech-synthesis-markup-language-ssml-reference.html#supported-symbols
Ihr müsst das so formatieren, sonst können wir damit nichts anfangen
![image](https://user-images.githubusercontent.com/11695964/50250059-1ae0ab80-03e0-11e9-8ee6-aeded38f6583.png)

**Comment by haerrel** [comment]
Videoanleitung zur Benutzung und Verifizierung der Sprach-Ausgabe in Whatsapp Gruppe

**Comment by LisaWenzl** [comment]
"Guad" wird teilweise nicht richtig ausgesprochen. Bei Testing aufgefallen im Ausdruck "sau guad". 
Bitte auch dafür bayrische Lautschrift einpflegen.

**Comment by haerrel** [comment]
Diese beiden Phrasen sind bei uns die einzigen mit "sau guad".
Beide haben das Lautschrift "guad" drin.

![image](https://user-images.githubusercontent.com/38572411/50950180-6a7b3a00-14a9-11e9-864a-c159143dd66f.png)

Hier ist z. B. eine Ausgabe die ich gerade erhalten habe:

> <speak>Sau <phoneme alphabet=\"ipa\" ph=\"gu:6_^d\">guad</phoneme>, München hat in dieser Kategorie viel zu bieten! Wie wäre es denn mit einem Besuch im Schwimmbad??</speak>

Die Lautschrift ist korrekt angegeben. Ist dieses Beispiel richtig ausgesprochen?
Ihr könnt das ja mal bei euch im Voice&Tone wiedergeben lassen:
![image](https://user-images.githubusercontent.com/38572411/50950443-40764780-14aa-11e9-8f83-4fdd7a1746ac.png)

Bitte schickt uns den Text aus dem "JSON Output Feld" immer mit. Das ist sehr wichtig für uns.
![image](https://user-images.githubusercontent.com/38572411/50950374-086f0480-14aa-11e9-8f57-61f4e26e8ec0.png)
