### ISSUE TITLE
Phrasen final einpflegen

### ISSUE THREAD

**Issue by haerrel** [sweIhm-ws2018-19/skillproject-fr-26#58]
@LisaWenzl  und @VanessaGMeiler werden bis 07.01. die finalen Phrasen herausarbeiten und diese werden dann vom Entwicklerteam final eingepflegt.

**Comment by LisaWenzl** [comment]
[Alexa Formulierungen.docx](https://github.com/sweIhm-ws2018-19/skillproject-fr-26/files/2730833/Alexa.Formulierungen.docx)

**Comment by hupling** [comment]
bbf515ae81c900b0866da03e32d749f0470639cf

**Comment by LisaWenzl** [comment]
Bitte nochmals überprüfen, einige Formulierungen wurden nicht laut unseren Vorgaben (siehe Dok.) geändert.
z.B. "noch mehr/andere tolle Aktivitäten" --> noch andere tolle Aktivitäten
      "Super Gschichtda" --> Super Gschicht

**Comment by haerrel** [comment]
Hab die zwei Fehler korrigiert.
Habe nach vergleichbaren Fehlern gesucht und nichts weiteres gefunden.

Eure Phrasen stehen bei uns hier im Code. Ist denke ich auch für einen Nicht-Entwickler einfach zu verstehen, da ja die Sätze eig. nahezu 1-zu-1 übernommen wurden. Für den Fall, dass ihr noch detaillierter bzw. genauer Suchen wollt.
https://github.com/sweIhm-ws2018-19/skillproject-fr-26/blob/master/MUCtivities/src/main/java/muctivities/constants/Phrases.java
