### ISSUE TITLE
"Spezielle" Ja/Nein Synonyme für Information und Vorschlag

### ISSUE THREAD

**Issue by VanessaGMeiler** [sweIhm-ws2018-19/skillproject-fr-26#61]
Es fehlen noch die Ja/Nein Synonyme, die speziell für Vorschlag und Information definiert wurden in der Datei "Nutzerantworten". 

z.B. "Ich brauche keine Information." oder "Auf Bowling/die Aktivität hab ich keine Lust."

-> Kann man die einfach alle in die allgemeinen Ja/Nein Synonyme einfügen oder muss man extra einen Intent oder Slot Type (was auch immer) dafür erstellen?

**Comment by hupling** [comment]
"Ich brauche keine Information." kann hinzugefügt werden einfach den AMAZON.NoIntent bzw AMAZON.YesIntent anpassen.

Bei dem anderen geht das leider nicht, da hier ein Platzhalter benötigt wird. In diesem Fall "Bowling" bzw. der Aktivitätsname. Die Amazon Intents unterstützen das leider nicht. Siehe Fehlermeldung im Screenshot.

![image](https://user-images.githubusercontent.com/11695964/50903538-5dfdcf80-141e-11e9-8a42-1e694cc583e7.png)
