### ISSUE TITLE
Formulierte Phrasen bei Nicht-Verstehen

### ISSUE THREAD

**Issue by VanessaGMeiler** [sweIhm-ws2018-19/skillproject-fr-26#62]
Wir hatten ja extra Phrasen formuliert, die Alexa sagen soll, wenn sie den Nutzer nicht versteht. Sie soll ihre Frage ja dann nochmal "einfacher" wiederholen. 
Das hatte anfangs ja eigentlich gut funktioniert, aber nach mehrmaligem Testen ist uns aufgefallen, dass sie das nicht mehr macht. 
Jetzt kommt fast immer, wenn sie etwas nicht versteht "Heute ist Regen angesagt...", egal bei welchem Intent man gerade ist.

**Comment by hupling** [comment]
das liegt glaube ich am auto lernen von alexa

**Comment by hupling** [comment]
neue version
![image](https://user-images.githubusercontent.com/11695964/50908151-6a3b5a00-1429-11e9-8efe-ace7ba336ecf.png)
alle phrasen gelöscht
![image](https://user-images.githubusercontent.com/11695964/50908182-7b846680-1429-11e9-9651-4fc13442ebb0.png)
