### ISSUE TITLE
Info - Wahl eines anderes Vorschlags

### ISSUE THREAD

**Issue by VanessaGMeiler** [sweIhm-ws2018-19/skillproject-fr-26#65]
Nach der Info ist es nicht möglich, einen neuen Vorschlag zu bekommen. Muss man da noch iwas verbinden oder Synonyme definieren oder so? Skill beenden nach der Info funktioniert. 
![image](https://user-images.githubusercontent.com/44700500/50923384-1e9aa780-144d-11e9-947c-a4a9500ffa89.png)

**Comment by LisaWenzl** [comment]
Gleiches Problem bei Tipp des Tages.
