### ISSUE TITLE
Fehler in der Formulierung bei "Nicht-Verstehen" 

### ISSUE THREAD

**Issue by VanessaGMeiler** [sweIhm-ws2018-19/skillproject-fr-26#66]
Die Nein-Option bei Nicht-Verstehen im Location-Intent fehlt ist uns aufgefallen, wär super wenn man die noch in der Formulierung einfügen könnte!
![image](https://user-images.githubusercontent.com/44700500/50924719-af26b700-1450-11e9-8914-80f7143216eb.png)

**Comment by hupling** [comment]
hinzugefügt
